spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:33060/start_over?characterEncoding=utf8&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: Yj6326076
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  application:
    name: core
  quartz:
    scheduler-name: quartz_job
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
logging:
  file:
    name: build/single.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
  logback:
    rollingpolicy:
      file-name-pattern: build/single-%d{yyyy-MM-dd}.%i.log
      max-file-size: 20MB
      max-history: 10
      total-size-cap: 100MB
management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /actuartor/z
